remote_theme: b2a3e8/jekyll-theme-console
style: dark
plugins:
  - jekyll-seo-tag
url: "https://vhf2235.github.io"

header_pages:
  - index.md

title: Vhf's homepage
description: Just some nonsence.

footer: 'This is a footer.'